tosca_definitions_version: cloudify_dsl_1_3

########################################################

imports:
  - http://www.getcloudify.org/spec/cloudify/4.0.1/types.yaml
  - http://www.getcloudify.org/spec/diamond-plugin/1.3.5/plugin.yaml
  - types/clearwater-monitoring.yaml
  - types/clearwater.yaml
  - types/snmp.yaml
  - types/bind.yaml

########################################################

inputs:

  private_domain:
    default: clearwater.local

  public_domain:
    default: example.com
